# Trigger when there exist a push to main branch

name: CI - portal template

on:
  push:
    branches: [ "main" ]

  workflow_dispatch: # allow manual trigger from github
    # Inputs the workflow accepts.
    inputs:
      name: 'inputA'
        description: 'input A description'
        # Default value if no value is explicitly provided
        default: 'test A'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      name: 'inputB'
        description: 'input B description'
        default: 'test B'
        required: false
        type: string

jobs:
  # job-name
  main: 
    # choice of os
    runs-on: ubuntu-latest 
    steps:
      # packages and dependencies (fill accordingly to your needs)
      - uses: actions/checkout@v4 #https://github.com/actions/checkout
      - uses: actions/setup-node@v4 #https://github.com/actions/setup-node
        with:
          node-version: 18
      # scripts
      - name: sanity test
        run: | 
          echo running sanity test
          ls
      - name: navigate target app
        run: cd test-app
      - name: build
        run: |
          npm install
          npm build
      - name: test
        run: npm test
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
