# Trigger when there exist a push to main branch
name: ci - main template

run-name: ${{ github.actor }} pushed to main

on:
  push:
    branches: [ "main" ]

  # Allow manual trigger from github
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      inputA:
        description: 'input A description'
        # Default value if no value is explicitly provided
        default: 'test A'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
      inputB:
        description: 'input B description'
        default: 'test B'
        required: false
        type: string

jobs:
  # job-name
  main: 
    # choice of os
    runs-on: ubuntu-latest 
    # optional setup your target directory, default would be root level
    defaults:
      run:
        working-directory: ./test-app
    steps:
      # packages and dependencies (fill accordingly to your needs)
      - name: Checkout
        uses: actions/checkout@v4 #https://github.com/actions/checkout
      - name: Setup Node  
        uses: actions/setup-node@v4 #https://github.com/actions/setup-node
        with:
          node-version: 18
      # scripts
      - name: Sanity Test
        run: | 
          echo running sanity test
          ls
      - name: Test
        run: npm run test
      - name: Build
        run: |
          npm install
          npm run build
      - name: Deploy
        run: |
          echo running deployment to distributor staging platform

