# This is a basic workflow that is manually triggered

name: test-deploy-workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # packages and dependencies (fill accordingly to your needs)
    - name: Checkout Repository
      uses: actions/checkout@v4 #https://github.com/actions/checkout
    - name: Setup Node  
      uses: actions/setup-node@v4 #https://github.com/actions/setup-node
      with:
        node-version: 18
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    # Runs a single command using the runners shell
    - name: Run deployment
      env:
        TOKEN: ${{ secrets.TOKEN }}
        APP_ID: ${{ secrets.APP_ID }}
        TESTERS: ${{ secrets.TEST_TESTER }}
      # Temporary disabled
      run: |
        echo "Running deployment..."
        npm install -g firebase-tools
        echo "bypass firebase cli"
        exit 0
        firebase appdistribution:distribute test-ci.apk \
          --app ${APP_ID} \
          --token ${TOKEN} \
          --release-notes "test release notes" \
          --testers ${TESTERS}
